changelog:
  categories:
    - title: 💣 Breaking Changes
      labels:
        - breaking-change
    - title: 🚀 Features
      labels:
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 📝 Documentation
      labels:
        - doc
    - title: 🧪 Tests
      labels:
        - test
    - title: 📦 Dependencies
      labels:
        - dependencies
    - title: 🛠️ Build
      labels:
        - build
    - title: 📌 Chore
      labels:
        - chore
  exclude:
    labels: [ci]
