version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mockable
      POSTGRES_PASSWORD: mockable
      POSTGRES_USER: mockable
    ports:
      - 5432:5432
    volumes:
      - ./docker-compose/db/init.sql:/docker-entrypoint-initdb.d/init.sql
