name: Cache

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref_name }}

on:
  push:
      branches: [main]
      paths:
      - "**.rs"
      - Cargo.toml

jobs:
  cache:
    name: Cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Rust
        id: rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ steps.rust.outputs.rustc_hash }}-${{ hashFiles('Cargo.toml') }}

      - name: Build (debug)
        uses: actions-rs/cargo@v1
        with:
          args: --all-features
          command: build
